---
# Workflows Naming Convention ref: https://www.pluralsight.com/blog/software-development/programming-naming-conventions-explained
# Workflows: (upper) Kebab case                               exp: Run-Unit-Tests
# Utility workflows: (lower) Kebab Case with underscoring     exp: _clone-repo

format_version: '12'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other
meta:
  bitrise.io:
    stack: osx-xcode-16.1.x
    machine_type_id: g2-m1.4core
trigger_map:
- pull_request_target_branch: dev
  pipeline: Pull-Request-Pipeline
pipelines:
  Pull-Request-Pipeline:
    stages:
    - Run-Checks: {}
stages:
  Run-Checks:
    workflows:
    - Run-Unit-Tests: {}
    - Run-Critical-Danger-Checks: {}
workflows:
  _clone-repo:
    steps:
    - activate-ssh-key:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone:
        inputs:
        - clone_depth: '100'
        asset_urls:
          icon.svg: https://bitrise-steplib-collection.s3.amazonaws.com/steps/git-clone/assets/icon.svg
  _set-pending-danger-statuses-for-pr:
    description: |-
      Utility workflow for setting Danger statuses required for PR as "Pending" with the link to Bitrise pipeline.
    steps:
    - github-status@3:
        title: GitHub Status for Danger Critical checks
        inputs:
        - set_specific_status: pending
        - status_identifier: danger/CriticalChecks
        - description: Running on Bitrise
        - auth_token: "$DANGER_GITHUB_API_TOKEN"
  bundler-installation:
    description: |-       
      Private workflow for installing (`install-bundler` step) and saving to cache. 
    steps:
    - install-bundler: {}
    - script:
        title: Set Ruby version to an env var
        inputs:
        - content: |-
            ruby_version=$(head -n 1 .ruby-version)
            envman add --key RUBY_VERSION --value "$ruby_version"
    - save-cache:
        title: Save Bundler cache
        inputs:
        - key: bundler-cache-{{ .Arch }}-{{ checksum "Gemfile.lock" }}
        - paths: |-
            ~/.rbenv/versions/$RUBY_VERSION
            ~/.asdf/installs/ruby/$RUBY_VERSION
  Install-Bundler:
    description: |- 
      Restoring Bundler from key-based cache (key is `bundler-cache-{{ .Arch }}-{{ checksum "Gemfile.lock" }}`).
      If cache was not restored - then installing (`install-bundler` step) and saving to cache. 
    steps:
    - restore-cache:
        title: Restore Bundler cache
        inputs:
        - key: bundler-cache-{{ .Arch }}-{{ checksum "Gemfile.lock" }}
    - bitrise-run:
        title: Bundler Installation and saving to cache
        run_if: '{{not (enveq "BITRISE_CACHE_HIT" "exact")}}'
        inputs:
        - workflow_id: bundler-installation
  Run-Critical-Danger-Checks:
    description: |-
      Rrunning Critical Danger checks defined in `DangerfileCriticalChecks`
    before_run:
    - _set-pending-danger-statuses-for-pr
    - _clone-repo
    - Install-Bundler
    steps:
    - script@1:
        title: Install Homebrew
        is_always_run: true
        inputs:
        - content: |-
            #!/usr/bin/env bash
            sh bootstrap.sh install_homebrew
    - script@1:
        title: Install Swiftlint
        is_always_run: true
        inputs:
        - content: |-
            #!/usr/bin/env bash
            sh bootstrap.sh install_swiftlint
    - script@1:
        title: Install Swiftformat
        is_always_run: true
        inputs:
        - content: |-
            #!/usr/bin/env bash
            sh bootstrap.sh install_swiftformat
    - script@1:
        title: Critical Danger checks
        is_always_run: true
        inputs:
        - content: |-
            #!/usr/bin/env bash
            # debug log
            set -x

            bundle exec danger --dangerfile=DangerfileCriticalChecks --danger_id=CriticalChecks --fail-on-errors=true
  Run-Unit-Tests:
    description: |- 
      Building Application and running Unit-Tests.
    before_run:
    - _clone-repo
    - Install-Bundler
    steps:
    - fastlane:
        timeout: 300
        inputs:
        - lane: unit_tests_build_for_testing
        title: Build App
    - script:
        title: Check warnings count
        is_skippable: true
        inputs:
        - content: |-
            #!/usr/bin/env bash
            # debug log
            set -x

            bundle exec danger --dangerfile=DangerWarningsCount --danger_id=WarningsCount --fail-on-errors=true
    - fastlane:
        timeout: 300
        inputs:
        - lane: unit_tests_run_without_building
        title: Run Unit-Tests
