desc "Build Unit-tests"
lane :unit_tests_build_for_testing do
  scan(
    device: ENV['TESTING_DEVICE'],
    scheme: ENV['TESTING_SCHEME'],
    project: ENV['PROJECT'],
    clean: true,
    build_for_testing: true,
    result_bundle: true,
    derived_data_path: ENV['DERIVED_DATA_PATH']
  )

  # Copy .xcresult file to source root directory for Danger analysis
  xcresult_path = lane_context[SharedValues::SCAN_GENERATED_XCRESULT_PATH]
  FileUtils.cp_r("#{xcresult_path}", "./../Plate8037.xcresult")
end

desc "Run Unit-tests without building"
lane :unit_tests_run_without_building do
  scan(
    device: ENV['TESTING_DEVICE'],
    scheme: ENV['TESTING_SCHEME'],
    project: ENV['PROJECT'],
    test_without_building: true,
    derived_data_path: ENV['DERIVED_DATA_PATH']
  )
end

desc "Run Unit-Tests with coverage"
lane :unit_tests do
  scan(
    device: ENV['TESTING_DEVICE'],
    scheme: ENV['TESTING_SCHEME'],
    project: ENV['PROJECT'],
    code_coverage: true,
    clean: true
  )
end

desc('Parse Unit-Tests coverage to a simple readable JSON using Slather (with Cobertura XML)')
desc('Update README.md file with the coverage percentage')
lane :parse_unit_tests_coverage do
  require 'json'
  require_relative 'Slather-Report-Parsing.rb'

  slather(
    cobertura_xml: true,
    output_directory: "test_output",
    proj: ENV['PROJECT'],
    scheme: ENV['TESTING_SCHEME']
  )

  coverage_data = parse_coverage_report("../test_output/cobertura.xml")
  coverage_percentage = 0
  json_report_path = "../code-coverage-report.json"
  File.open(json_report_path, 'w') do |file|
    coverage_percentage = ((coverage_data.covered_lines.to_f / coverage_data.total_lines.to_f) * 100).round(2)
    code_coverage_record = {
      "covered_lines": coverage_data.covered_lines,
      "total_lines": coverage_data.total_lines,
      "coverage_percentage": coverage_percentage
    }
    file.puts(code_coverage_record.to_json)
  end
  sh("cat #{json_report_path}")

  readme_path = "../README.md"
  File.open(readme_path, 'w') do |file|
    file.puts("**Current Unit-Tests coverage**: #{coverage_percentage}%")
  end
  sh("cat #{readme_path}")
end
