name: Danger

on:
  pull_request:

jobs:
  Danger:

    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      DANGER_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run Danger
        run: bundle exec danger --danger_id=DefaultChecks --fail-on-errors=true
