name: Danger

on:
  pull_request:

jobs:
  Danger:

    runs-on: macos-15
    timeout-minutes: 2
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.0.1.app/Contents/Developer
      DANGER_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install Homebrew
        run: sh bootstrap.sh install_homebrew

      - name: Install Swiftlint
        run: sh bootstrap.sh install_swiftlint

      - name: Install Swiftformat
        run: sh bootstrap.sh install_swiftformat

      - name: Run Danger
        run: bundle exec danger --fail-on-errors=true
