name: Default milestone

on:
  pull_request:
    types: [opened]

jobs:
  default_milestone:

    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/github-script@v6
        if: |
          ! github.event.pull_request.milestone
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const infra_milestone_number = 4
            const infra_milestone = "Infra"
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              milestone: infra_milestone,
            });
